# 基础镜像
FROM redis
# author
MAINTAINER fanxin

# 挂载目录
VOLUME /home/fanxin/redis
# 创建目录
RUN mkdir -p /home/fanxin/redis
# 指定路径
WORKDIR /home/fanxin/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/fanxin/redis/redis.conf
