# 基础镜像
FROM nginx
# author
MAINTAINER fanxin

# 挂载目录
VOLUME /home/fanxin/projects/fanxin-ui
# 创建目录
RUN mkdir -p /home/fanxin/projects/fanxin-ui
# 指定路径
WORKDIR /home/fanxin/projects/fanxin-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/fanxin/projects/fanxin-ui
