# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER fanxin

# 挂载目录
VOLUME /home/fanxin
# 创建目录
RUN mkdir -p /home/fanxin
# 指定路径
WORKDIR /home/fanxin
# 复制jar文件到路径
COPY ./jar/fanxin-modules-file.jar /home/fanxin/fanxin-modules-file.jar
# 启动文件服务
ENTRYPOINT ["java","-jar","fanxin-modules-file.jar"]