# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER fanxin

# 挂载目录
VOLUME /home/fanxin
# 创建目录
RUN mkdir -p /home/fanxin
# 指定路径
WORKDIR /home/fanxin
# 复制jar文件到路径
COPY ./jar/fanxin-auth.jar /home/fanxin/fanxin-auth.jar
# 启动认证服务
ENTRYPOINT ["java","-jar","fanxin-auth.jar"]